### PR TITLE
tiny readme fix

### PR DESCRIPTION
**Pull request by o69mar**
what if you just put a nix flake on the root of the repo? ppl will have no problem with it and it's not gonna be that much files on root as the git app repo.

i also had to modify `CMakeLists.txt` (not on the PR) to build clipboard with wayland support

### CODE REVIEW

**Comment by Slackadays** [comment]
Needs a rebase

**Comment by o69mar** [comment]
oh

**Comment by Slackadays** [comment]
@o69mar I don't think we should add a flake to the top of the repo because there are only 8 items there, and keeping it cluter-free is my top priority. The longer the list is, the more people have to scroll to read the papaya smoothie story. :yum:

**Comment by o69mar** [comment]
> @o69mar I don't think we should add a flake to the top of the repo because there are only 8 items there, and keeping it cluter-free is my top priority. The longer the list is, the more people have to scroll to read the papaya smoothie story. :yum: 

why not just add the flake to a directory?

**Comment by Slackadays** [comment]
That could word, what directory do you think would be best for the flake?

**Comment by Slackadays** [comment]
@o69mar any progress on this?

**Comment by o69mar** [comment]
> That could work, what directory do you think would be best for the flake?

maybe the src folder, or maybe a nix folder

**Comment by o69mar** [comment]
> @o69mar any progress on this?

maybe i'll open a new PR if you want the flake

**Comment by Slackadays** [comment]
Going to close this if there is no more activity 

@o69mar I don't think we can safely add a nix flake, because we shouldn't focus on things we can't control (nix packages)

**Comment by o69mar** [comment]
> @o69mar I don't think we can safely add a nix flake, because we shouldn't focus on things we can't control (nix packages)

but the flakes work fine though. and it's easy to configure, i also switched to arch again so i can't test it anymore

**Comment by Slackadays** [comment]
Let's try to focus on the C++ parts of CB which we are totally in control of

**Comment by o69mar** [comment]
> Let's try to focus on the C++ parts of CB which we are totally in control of

yeah, and also what if clipboard was rewritten in rust? or you just don't like rust or you haven't learn't it

**Comment by Slackadays** [comment]
I don't know, because even if clipboard was in rust, we wouldn't want a nix flake because we don't control nix.

**Comment by o69mar** [comment]
> I don't know, because even if clipboard was in rust, we wouldn't want a nix flake because we don't control nix.

okay

**Pull request closed without merging**
