### PR TITLE
add nix flake

### PR DESCRIPTION
**Pull request by o69mar**
i tested it and it worked, however it shows the version is 0.3.1, the nix flake installs clipboard from the releases page.

i named the pkg `slackadays-clipboard` because there was a pkg called `clipboard` already at nixpkgs. also make sure to update the sha256, rev (a release at the releases page) and version when there is a new release. you can get the sha256 by using `nix-prefetch-github`, with the command if for example, 0.3.3 was released:  `nix-prefetch-github Slackadays Clipboard --rev 0.3.3`

you can find it's github page here: https://github.com/seppeljordan/nix-prefetch-github

### CODE REVIEW

**Comment by Slackadays** [comment]
If a nix flake involves adding an extra file to the project, then I don't know if that would be the best option. Clipboard should be as generic as possible and I feel like adding a packager specific file like this adds clutter.

**Comment by o69mar** [comment]
> If a nix flake involves adding an extra file to the project, then I don't know if that would be the best option. Clipboard should be as generic as possible and I feel like adding a packager specific file like this adds clutter.

should i put the flakes on a folder (e.g a folder called `nix`)

**Comment by Slackadays** [comment]
I wanted to keep the root directory as simple as possible because more assets clutter up the GH homepage which makes the project less user friendly.

**Comment by o69mar** [comment]
> I wanted to keep the root directory as simple as possible because more assets clutter up the GH homepage which makes the project less user friendly.

alright, i moved the flake to the nix folder.

**Comment by Slackadays** [comment]
Right now, I think it might be best to focus on making a nix package or improving Clipboard itself

**Comment by o69mar** [comment]
> Right now, I think it might be best to focus on making a nix package or improving Clipboard itself

someone already created a PR which adds clipboard to nixpkgs (https://github.com/NixOS/nixpkgs/pull/207928)

**Comment by Slackadays** [comment]
Looks like there are a few issues that that could be fixed, so you could help out there! I don't know much of Nix but you do :)

**Comment by o69mar** [comment]
> Looks like there are a few issues that that could be fixed, so you could help out there! I don't know much of Nix but you do :)

PRS rarely get merged in the nixpkgs repo.

**Pull request closed without merging**
