### PR TITLE
add shell scripts to make the installation a bit easy

### PR DESCRIPTION
**Pull request by gentoo-btw**
i haven't tested this on windows/freebsd. im not sure if it works on both of these. 
i created a batch file for windows (named `install-win.bat`) and one for linux/freebsd (named `install.sh`)

### CODE REVIEW

**Comment by Slackadays** [comment]
I like this a lot better, see if you can rename install-win.bat to just install.bat, and add cases for OpenBSD and other OSes in install.sh.

**Comment by gentoo-btw** [comment]
> I like this a lot better, see if you can rename install-win.bat to just install.bat, and add cases for OpenBSD and other OSes in install.sh.
> 
> Then we can try out this new install system and see if it works out :)

alright, the changes are made, hope it works.

**Comment by Slackadays** [comment]
I don't see any cases for those other OSes in install.sh, but it should look identical to Linux or FreeBSD.

**Comment by gentoo-btw** [comment]
> I don't see any cases for those other OSes in install.sh, but it should look identical to Linux or FreeBSD.

should i just add unix? you only put bsd/linux/windows in the readme tho

**Comment by Slackadays** [comment]
the generic form would be just be identical to the linux version, so although you could say unix/solaris, it would really be all other platforms

**Comment by Slackadays** [comment]
sorry if I seem fussy or picky, but I want to make sure everything that goes into Clipboard is the highest quality possible

**Comment by gentoo-btw** [comment]
> sorry if I seem fussy or picky, but I want to make sure everything that goes into Clipboard is the highest quality possible

idk if it works on unix/solaris. I only put the platforms you mentioned on the readme.

**Comment by Slackadays** [comment]
> idk if it works on unix/solaris. I only put the platforms you mentioned on the readme.

I mentioned "anything that supports C++20" so that could mean just about any platform out there, just as long as they support CMake and a C++20 compiler

**Comment by gentoo-btw** [comment]
> > idk if it works on unix/solaris. I only put the platforms you mentioned on the readme.
> 
> I mentioned "anything that supports C++20" so that could mean just about any platform out there, just as long as they support CMake and a C++20 compiler

ohhh, alright I'll add unix/solaris soon

**Comment by gentoo-btw** [comment]
> > idk if it works on unix/solaris. I only put the platforms you mentioned on the readme.
> 
> I mentioned "anything that supports C++20" so that could mean just about any platform out there, just as long as they support CMake and a C++20 compiler

okay, I put unix/solaris and also macos

**Comment by Slackadays** [comment]
we also need a "generic" case that should work generically, because if you run the script and your platform is not in there, then you're out of luck while the script should be able to do as much as it can. also, see if you can remove the numbers from the section titles and the $ from the command examples, because I want the document to be as clean as possible and those actually make it more confusing.

**Comment by gentoo-btw** [comment]
alright, i'll fix the readme. also my platform is there. which is linux

**Comment by Slackadays** [comment]
I've just realized that instead of making a script to make manual installation easier, it might be better to focus on making Clipboard packages for distros like Gentoo. Then, we can leave the readme instructions the same as they were before. You may want to close this PR or rename it to adding a Gentoo package option to the readme instead

**Comment by gentoo-btw** [comment]
> I've just realized that instead of making a script to make manual installation easier, it might be better to focus on making Clipboard packages for distros like Gentoo. Then, we can leave the readme instructions the same as they were before. You may want to close this PR or rename it to adding a Gentoo package option to the readme instead

if i can figure out how to write an ebuild. i might make a gentoo clipboard package. but i have to either choose to publish it on the main gentoo repo. or the other gentoo overlays. and if the clipboard package is on a gentoo overlay rather than the main gentoo repo. it requires you to put `eselect repository` on the readme.

**Comment by Slackadays** [comment]
That sounds great, and we might be able to make it onto the main Gentoo repo because CB is so easy to build and now useful it is. Making an ebuild shouldn't be that hard compared to other packages because all you need is GCC 11 or 12 and CMake

**Comment by gentoo-btw** [comment]
i have gcc/ccache and cmake so i could make the ebuild. and publish it as `app-misc/clipboard`

**Comment by Slackadays** [comment]
Looks like GNU coreutils and some other related packages are under sys-apps, so that might work even better than apps-misc because Clipboard is almost essential for those who use it.

**Comment by gentoo-btw** [comment]
> Looks like GNU coreutils and some other related packages are under sys-apps, so that might work even better than apps-misc because Clipboard is almost essential for those who use it.

alright

**Comment by gentoo-btw** [comment]
> Looks like GNU coreutils and some other related packages are under sys-apps, so that might work even better than apps-misc because Clipboard is almost essential for those who use it.

bro, i keep getting errors about the src directory missing. and it tries to find "clipboard-0.1.3" but it's actually "Clipboard-0.1.3"

**Comment by Slackadays** [comment]
Weird, have you done anything specific to make it look for Clipboard-0.1.3 and not clipboard-0.1.3?

**Comment by gentoo-btw** [comment]
> Weird, have you done anything specific to make it look for Clipboard-0.1.3 and not clipboard-0.1.3?


> Weird, have you done anything specific to make it look for Clipboard-0.1.3 and not clipboard-0.1.3?

it gets even worse, i set the build dir. and now it outputs `line 11: /var/tmp/portage/app-misc/clipboard-0.1.3/work/Clipboard-0.1.3: No such file or directory` even tho it exists when i try to cd into it. now i give up trying to fix this bruh.

**Comment by Antiz96** [comment]
If it helps, here's a [link](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clipboard) to the PKGBUILD I made for the AUR.
Maybe you can take inspiration from it? 

Hope it helps :)

**Comment by gentoo-btw** [comment]
> > Weird, have you done anything specific to make it look for Clipboard-0.1.3 and not clipboard-0.1.3?
> 
> it gets even worse, i set the build dir. and now it outputs `line 11: /var/tmp/portage/app-misc/clipboard-0.1.3/work/Clipboard-0.1.3: No such file or directory` before it extracts the .tar.gz archive. even tho it exists when i try to cd into it. i'm done trying to publish the gentoo pkg.

hmm.. is it because I forgot to put " "?

**Comment by gentoo-btw** [comment]
bro this PR is outdated bro 💀

**Pull request closed without merging**
