### PR TITLE
Add Clang format

### PR DESCRIPTION
**Pull request by Davipb**
This PR adds `clang-format` and configures a CI workflow to ensure that the format is being followed for all commits. I used a code style I'm familiar with as a base but we can easily edit `.clang-format` as needed to customize it.

Note that since this is a formatting PR, it has a rather large diff because it formats all existing source code files. It may be easier to just review the first commit in the PR, "Add clang-format", since it has all of the actual changes. The second commit, "Format files", is just running blindly running `clang-format` on all files.

### CODE REVIEW

**Comment by Slackadays** [comment]
I like how this is done so far. However, I have the following questions:
- What exactly should do action do? One option is to have it automatically modify the code that it formats. However, this adds the possibility of bugs getting automatically added if there is a clang-format bug or something else that depends on a specific formatting. Another option is to integrate the formatting as a Clipboard Test so that any code that isn't already correctly formatted causes a test failure.
- What's the best format we should use? I noticed that the starting point here has 2 space indents. I'm personally used to 4 spaces or a single tab, so that's something we could change.
- Should we integrate clang-format into CMake, independent scripts (this is the current method), or keep it all in GHA? Personally, I would prefer to keep dependencies to a minimum, which means CMake is mostly out. Right now it looks like we're in a good position regarding the other options.

**Comment by Davipb** [comment]
> What exactly should do action do? One option is to have it automatically modify the code that it formats. However, this adds the possibility of bugs getting automatically added if there is a clang-format bug or something else that depends on a specific formatting. Another option is to integrate the formatting as a Clipboard Test so that any code that isn't already correctly formatted causes a test failure.

I'm not sure I get this question. Right now I added two scripts `clang-format.{sh,ps1}` and `clang-format-check.{sh,ps1}`. The first one will call `clang-format -i` to rewrite files in-place to follow the code style, while the second one will call it with `--dry-run` to just check if the files follow the code style without modifying anything. 

`clang-format.sh` is meant to be used by contributors before committing their work, and it shouldn't have any semantic changes to the code since `clang-format` itself guarantees that. The Github Workflow calls `clang-format-check.sh`, which means it'll fail the check if any file isn't following the code style without modifying anything.

> What's the best format we should use? I noticed that the starting point here has 2 space indents. I'm personally used to 4 spaces or a single tab, so that's something we could change.

The format is fully configurable in `.clang-format` and is just a matter of taste. Like I mentioned I chose one I had in handy as a base but we can change it as needed.

> Should we integrate clang-format into CMake, independent scripts (this is the current method), or keep it all in GHA? Personally, I would prefer to keep dependencies to a minimum, which means CMake is mostly out. Right now it looks like we're in a good position regarding the other options.

Integrating it into CMake is a bit painful because we'd have to somehow grab all source and header files from CMake target properties (which isn't trivial) and create custom targets to call clang-format. Since most IDEs already have native support for `.clang-format` and code style isn't very useful for someone that just wants to compile code on the command line, I didn't see much of a benefit going through that route.

**Comment by Davipb** [comment]
I've updated the style to use 4-space indents

**Comment by Slackadays** [comment]
> `clang-format.sh` is meant to be used by contributors before committing their work, and it shouldn't have any semantic changes to the code since `clang-format` itself guarantees that. The Github Workflow calls `clang-format-check.sh`, which means it'll fail the check if any file isn't following the code style without modifying anything.

I think what I was trying to ask here is what action the linting GH Action should take for the code that it processes. Should it automatically modify the code in place and replace what's in the repo with the new formatted versions? Or should it act as a test and fail if any file isn't following the code style? Since you mention that it already acts as a test, the second option is the way to go here.

**Pull request merged**
