### PR TITLE
add makefile to make clipboard installation easy

### PR DESCRIPTION
**Pull request by gentoo-btw**
you can install clipboard by compiling, installing it yourself. but why not add a makefile to make the install process easier? (for users who doesn't wanna manually install clipboard)

### CODE REVIEW

**Comment by gentoo-btw** [comment]
> You can install clipboard by compiling, installing it yourself. but why not add a makefile to make the install process easier? (for users who doesn't wanna manually install clipboard)

**Comment by gentoo-btw** [comment]
oops, i accidentally closed the pr

**Comment by Slackadays** [comment]
The one thing I don't like about this is how it ironically adds more complexity to installation because you have to think more about what platform you're on, and it doesn't account for FreeBSD having sudo but OpenBSD doas (the makefile uses doas for all BSDs). Also, it adds a dependency on Make which we can't assume exists. 

I think the fix for this would be to have a shell script (batch file for win) that wraps CMake and doesn't depend on Make. Would this be possible instead of a Makefile?

**Comment by gentoo-btw** [comment]
> The one thing I don't like about this is how it ironically adds more complexity to installation because you have to think more about what platform you're on, and it doesn't account for FreeBSD having sudo but OpenBSD doas (the makefile uses doas for all BSDs). Also, it adds a dependency on Make which we can't assume exists.
> 
> I think the fix for this would be to have a shell script (batch file for win) that wraps CMake and doesn't depend on Make. Would this be possible instead of a Makefile?

or maybe just remove `test -f` stuff and fix the sudo/doas conflict?

**Comment by Slackadays** [comment]
Is there some way for us to not depend on Make?

**Comment by gentoo-btw** [comment]
> Is there some way for us to not depend on Make?

hmm.. i could make it a shell script.

**Comment by gentoo-btw** [comment]
> Is there some way for us to not depend on Make?

or

**Comment by gentoo-btw** [comment]
bro why do i keep accidentally clicking the close with comment button

**Comment by supsm** [comment]
There is already cmake which makes this unnecessary

**Comment by gentoo-btw** [comment]
> There is already cmake which makes this unnecessary, it’s only around 2 commands anyways

yeah, but the makefile also executes these commands

**Comment by Slackadays** [comment]
I feel like we should cancel the PR unless there is some way to make the documentation simpler and have a shell script instead

**Comment by gentoo-btw** [comment]
> I feel like we should cancel the PR unless there is some way to make the documentation simpler and have a shell script instead

yeah, maybe next time i'll do a PR. but this time it's a shell script.

**Pull request closed without merging**
