### PR TITLE
fix nixos problem on `install.sh`

### PR DESCRIPTION
**Pull request by o69mar**

### CODE REVIEW

**Comment by Slackadays** [comment]
Instead of repeating the compile code, see if you can jump to it from the Linux section that's already there

**Comment by Slackadays** [comment]
The code has to be fully deduplicated, and this means jumping to https://github.com/Slackadays/Clipboard/blob/a5792784660257af46b5dca6928b0f27cd2efb73/src/install.sh#L60

instead of making a whole new code block for Nix

**Comment by o69mar** [comment]
ges

**Comment by Slackadays** [comment]
See if `mkdir ~/.local/bin` could be moved to the Nix section, and it looks like the script will fail on Nix because it doesn't know to skip to the compile section from the generic Linux one

**Comment by o69mar** [comment]
> See if `mkdir ~/.local/bin` could be moved to the Nix section, and it looks like the script will fail on Nix because it doesn't know to skip to the compile section from the generic Linux one

should i just move it to the first lines?

**Comment by Slackadays** [comment]
In the compile section, add a check for Nix that only does Nix stuff, and add `mkdir ~/.local/bin` there

**Comment by o69mar** [comment]
> In the compile section, add a check for Nix that only does Nix stuff, and add `mkdir ~/.local/bin` there

made the changes

**Comment by Slackadays** [comment]
`mkdir ~/.local/bin` is not under the Nix section

**Comment by o69mar** [comment]
> `mkdir ~/.local/bin` is not under the Nix section

fixed it

**Comment by Slackadays** [comment]
This looks good, but also don't forget about `libclipboardx11.so` and `libclipboardwayland.so` as well, and there isn't any way for the script to jump to the Nix section from the generic Linux one. :smiley:

**Comment by o69mar** [comment]
> This looks good, but also don't forget about `libclipboardx11.so` and `libclipboardwayland.so` as well, and there isn't any way for the script to jump to the Nix section from the generic Linux one. smiley

i think i have to move it somewhere in the linux section or keep it there, also cmake compiles clipboard without any x11/wayland support

**Comment by Slackadays** [comment]
CMake may or may not compile with X11/Wayland support, it just depends on what packages you have available. Have you considered other methods of making sure that Nix will only run the compile code without placing the compile code before everything else?

**Comment by Slackadays** [comment]
You could use bash functions, and I think you might have to install special header packages to compile with X11/Wayland.

**Comment by o69mar** [comment]
> You could use bash functions, and I think you might have to install special header packages to compile with X11/Wayland.

what if i add a ``--install-for-nixos`` argument?

**Comment by Slackadays** [comment]
That would be getting too complicated for users as the whole point of the scripts is to keep everything simple, so what you could do is move the entire compile section to a function, replace the part where the section is right now with a call to that function, and check for Nix at the very beginning and jump to that function if you're using Nix

**Comment by o69mar** [comment]
> That would be getting too complicated for users as the whole point of the scripts is to keep everything simple, so what you could do is move the entire compile section to a function, replace the part where the section is right now with a call to that function, and check for Nix at the very beginning and jump to that function if you're using Nix

oh alright

**Comment by o69mar** [comment]
> That would be getting too complicated for users as the whole point of the scripts is to keep everything simple, so what you could do is move the entire compile section to a function, replace the part where the section is right now with a call to that function, and check for Nix at the very beginning and jump to that function if you're using Nix

made the changes

**Comment by Slackadays** [comment]
Replace the compile section at the end of the script with a call to `compile_section` and include all Nix logic in `compile_section` so that it can be used generically for all platforms

**Comment by o69mar** [comment]
> Replace the compile section at the end of the script with a call to `compile_section` and include all Nix logic in `compile_section` so that it can be used generically for all platforms

the compile_section part has to stay at the top, or it will say `line 7: compile_section: command not found`

**Comment by Slackadays** [comment]
The compile_part can stay on top, but everything that has to do with compiling should stay in there to deduplicate code

**Comment by o69mar** [comment]
> The compile_part can stay on top, but everything that has to do with compiling should stay in there to deduplicate code

oh okay

**Comment by Slackadays** [comment]
Now the compile_section assumes that you're running Nix, which many users aren't. See if you can move the stuff specific to Nix to its own block within the function that checks if you're using Nix or not

**Comment by Slackadays** [comment]
I like this! However, we don't actually know that we're using Linux when installing though compiling, so only show a message for Nix

**Comment by o69mar** [comment]
> I like this! However, we don't actually know that we're using Linux when installing though compiling, so only show a message for Nix

finally, the PR can be merged

**Pull request merged**
