### PR TITLE
add the package status to the readme

### PR DESCRIPTION
**Pull request by o69mar**

### CODE REVIEW

**Comment by Slackadays** [comment]
I would appreciate it if the package status was just moved to where "Arch-Linux users..." is do it can replace that text with something more generic

**Comment by o69mar** [comment]
> I would appreciate it if the package status was just moved to where "Arch-Linux users..." is do it can replace that text with something more generic

i made the changes

**Comment by Slackadays** [comment]
Maybe I wasn't clear enough, so all I wanted compared to how the readme was at the beginning was the `Arch-Linux users...` completely replaces by the package monitor, nothing else moved or changed.

**Comment by o69mar** [comment]
> Maybe I wasn't clear enough, so all I wanted compared to how the readme was at the beginning was the `Arch-Linux users...` completely replaced by the package monitor, nothing else moved or changed.

alright, i made the changes.
also `cb --help` thinks the version is 0.2.0 for some reason

**Comment by Slackadays** [comment]
I was hoping for the distrowatch widget in place of the text specific to Arch and Alpine, and you could fix the 0.2.0 issue if you want :)

**Comment by Slackadays** [comment]
Unfortunately, the changes to the readme aren't up to Clipboard's code quality standards, so I decided to do it myself.

**Comment by o69mar** [comment]
> Unfortunately, the changes to the readme aren't up to Clipboard's code quality standards, so I decided to do it myself.

aw man, even i made a spelling mistake in the patch.

**Pull request closed without merging**
