### PR TITLE
fix some `install.sh` problems

### PR DESCRIPTION
**Pull request by o69mar**
maybe not installing the `.so` files wasn't a good idea..
image

i also switched to hyprland

### CODE REVIEW

**Comment by Slackadays** [comment]
See if you could add installing the .so files as well

**Comment by Slackadays** [comment]
@o69mar Were you planning on moving the `libclipboardx11.so` and `libclipboardwayland.so` files if they're present?

**Comment by o69mar** [comment]
i would just copy the .so files if they are not present

**Comment by o69mar** [comment]
> @o69mar Were you planning on moving the `libclipboardx11.so` and `libclipboardwayland.so` files if they're present?

you prob would have to make changes to the cmakelists file and also clipboard, just so clipboard can recognize the file. and cmake knowing where is the wayland/x11 lib on nixos

image

**Comment by Slackadays** [comment]
> you prob would have to make changes to the cmakelists file and also clipboard, just so clipboard can recognize the file. and cmake knowing where is the wayland/x11 lib on nixos

This doesn't matter at all, because the files are always going to be in the same place no matter where CMake finds them

**Comment by o69mar** [comment]
oh

**Comment by Slackadays** [comment]
Why are the lines for `libclipboardx11.so` and `libclipboardwayland.so` files missing?

**Comment by o69mar** [comment]
> Why are the lines for `libclipboardx11.so` and `libclipboardwayland.so` files missing?

because they do nothing on nixos, even if they are installed to ~/.local/bin, and clipboard still complains that there are no .so files

**Comment by Slackadays** [comment]
We don't know that they won't exist on nixos, since they only depend on CMake finding X11/Wayland libraries to use first. It just didn't work on your specific system so it's nice to think about other systems too.

**Comment by o69mar** [comment]
> We don't know that they won't exist on nixos, since they only depend on CMake finding X11/Wayland libraries to use first. It just didn't work on your specific system so it's nice to think about other systems too.

okay, i will put the lines back for the .so's

**Comment by Slackadays** [comment]
Why is there a download link for Clipboard in the compile section?

**Comment by o69mar** [comment]
> Why is there a download link for Clipboard in the compile section?

that's used to get the precompiled so files

**Comment by Slackadays** [comment]
But if you download Clipboard to get the `.so` files, we don't know that they're going to work. Also, I realized that you might need a NixOS installation step not just for compiling, but also for downloading. See if you could add a check for Nix in the Linux download section and have special steps for Nix there

**Comment by o69mar** [comment]
> But if you download Clipboard to get the `.so` files, we don't know that they're going to work. Also, I realized that you might need a NixOS installation step not just for compiling, but also for downloading. See if you could add a check for Nix in the Linux download section and have special steps for Nix there
> 
> For the `.so` files, just assume they exist even though CMake on your system didn't find them this time

also what if clipboard was patched to not show the .so errors and cmake finding the .so's at the correct dir (`/run/current-system/sw/lib/`)

**Comment by Slackadays** [comment]
This already happens if you don't compile Clipboard in Debug mode, so you just need to set `-DCMAKE_BUILD_TYPE=MinSizeRel` when doing `cmake ..` to not show the messages.

**Comment by o69mar** [comment]
> This already happens if you don't compile Clipboard in Debug mode, so you just need to set `-DCMAKE_BUILD_TYPE=MinSizeRel` when doing `cmake ..` to not show the messages.

oh, alright

**Comment by Slackadays** [comment]
There are a few conflicts now, would you mind working on them?

**Comment by o69mar** [comment]
> There are a few conflicts now, would you mind working on them?

sure

**Comment by o69mar** [comment]
> There are a few conflicts now, would you mind working on them?

fixed it

**Comment by Slackadays** [comment]
I can't find where the Nix code is actually run in the script, and it looks like you might be making a tmpdir again because one is already made elsewhere. One more thing, also don't forget to move libclipboardx11.so and libclipboardwayland.so if they exist. There are a few existence checks in the script elsewhere, so use those as a template :)

**Comment by Slackadays** [comment]
@o69mar At this point, it might be better if you started the Nix part from scratch because the script has changed enough to make Nix easier but the existing method doesn't fit well

**Comment by Slackadays** [comment]
Shellcheck failed

**Comment by o69mar** [comment]
> Shellcheck failed

it should not fail now

**Comment by Slackadays** [comment]
Two more tiny changes:
- Change the double periods `..` in the messages to three periods `...` or none at all
- See if you can re-use the regular tmpdir instead of making another one just for Nix

**Comment by o69mar** [comment]
> Two more tiny changes:
> 
> * Change the double periods `..` in the messages to three periods `...` or none at all
> * See if you can re-use the regular tmpdir instead of making another one just for Nix

fixed it

**Comment by Slackadays** [comment]
I still see them here 
image
image

**Comment by o69mar** [comment]
that should be fixed

**Comment by Slackadays** [comment]
There is still an extraneous tmpdir creation down below, and there should be a check for libclipboardx11.so and libclipboardwayland.so too

**Comment by o69mar** [comment]
> There is still an extraneous tmpdir creation down below, and there should be a check for libclipboardx11.so and libclipboardwayland.so too

fixed

**Comment by Slackadays** [comment]
What if you downloaded Clipboard using the link entirely instead of compiling it?

**Comment by o69mar** [comment]
> What if you downloaded Clipboard using the link entirely instead of compiling it?

good idea, i won't apply it to the nix section because it points to the wrong interpreter on nixos

**Comment by Slackadays** [comment]
I forgot :(

Does it work with the X11/Wayland libraries compiled for the separate interpreter?

**Comment by o69mar** [comment]
> I forgot :(
> 
> Does it work with the X11/Wayland libraries compiled for the separate interpreter?
> 
> Actually, you don't need to download Clipboard at all, so just leave in the X11/Wayland file checks and that's it :)

oh wait i made changes before reading this msg :skull:

**Comment by o69mar** [comment]
> I forgot :(
> 
> Does it work with the X11/Wayland libraries compiled for the separate interpreter?

idk man, clipboard also complains that it can't find the .so's

> Actually, you don't need to download Clipboard at all, so just leave in the X11/Wayland file checks and that's it :)

that should be it

**Comment by o69mar** [comment]
> I forgot :(
> 
> Does it work with the X11/Wayland libraries compiled for the separate interpreter?
> 
> Actually, you don't need to download Clipboard at all, so just leave in the X11/Wayland file checks and that's it :)

works perfectly (fixed the "Clipboard Installed Successfully" problem)

**Comment by Slackadays** [comment]
I think it might be a better idea now to make a nix flake, because we can't depend on there being an amd64 system for the downloaded libs to work on

**Comment by o69mar** [comment]
> I think it might be a better idea now to make a nix flake, because we can't depend on there being an amd64 system for the downloaded libs to work on

i will use a random flake example because idk how to code a flake. and if it works, i will close this PR and make a new one

**Comment by o69mar** [comment]
#91

**Pull request closed without merging**
