### PR TITLE
Make X11 and Wayland optional

### PR DESCRIPTION
**Pull request by Davipb**
As discussed in #14, this PR makes X11 and Wayland optional for Linux by separating them into individual `.so` files and dynamically loading them at runtime.

Some additional changes that had to be made:
* A new interface-only target `gui` was created to store headers shared between the main executable and the X11/Wayland shared objects.
  * `logging.cpp` in special was deleted and rolled into `logging.hpp`, making `debugStream` static instead of extern to avoid having to create a static library. Since this stream is only used for debugging, that shouldn't be an issue.
* The RPATH was modified to include `$ORIGIN`, which allows the `.so` files to be located in the same folder as the executable. This is useful for debugging or standalone packaging.
* The CMAKE install script as modified to put the shared objects in `/usr/local/lib` (or whichever install prefix the user chose + /lib)
* The github workflows and install scripts were modified to build the project in a `./build` subfolder. This is called an "out of source build" and is a recommended CMake pratice because it avoids mixing temporary build files and source code files. In our case it was necessary since some files were conflicting with the new CMake targets.
  * The install scripts were also modified to use their native command tracing options instead of a custom function (`set -x` on bash, `Set-PSDebug -Trace 1` on PowerShell)
* The github workflows were modified to get all output files when packaging the workflow result
  * The CMake build script checks for the `CI` environment variable and puts all relevant files in a predictable location to allow for this

### CODE REVIEW

**Comment by Slackadays** [comment]
Would it be possible to put all the new folders/files under `clipboard` or `src` so that we don't add any new assets to the root-level directory? Right now, there are 4 directories and 6 files, and I'm personally uncomfortable with increasing these counts any further, as they make Clipboard's filesystem less "clean" to new users and requires more scrolling to view the readme.

**Comment by Davipb** [comment]
> Would it be possible to put all the new folders/files under `clipboard` or `src` so that we don't add any new assets to the root-level directory?

That's not the standard I usually see in CMake projects but sure, I guess we can have an intermediary folder there.

> One more thing I just noticed: it looks like we're assuming X11/Wayland to be running on Linux, but we can't guarantee this because the BSDs (and OpenIndiana) support X11 and FreeBSD is switching to Wayland now, all of which Clipboard is supposed to support. So, it might not be good to put all our eggs in the Linux basket.

Hm, since there are only CI tests for Linux, Windows, and Mac I kind of assumed those were the main targets and everything else was a "bonus". `dlopen` seems to be a Linux thing and not a Unix thing, so I guess every OS is going to have their own implementation of dynamic linking at runtime. 

I'm not familiar at all with the OSs you mentioned there, so I wouldn't really know where to start in supporting them without a lot of research and testing. Maybe we can keep this in a branch until we figure out how to do the dynamic linking at runtime thing on every supported platform?

**Comment by Slackadays** [comment]
> That's not the standard I usually see in CMake projects but sure, I guess we can have an intermediary folder there.

I know this isn't the standard, but one of the goals of Clipboard is ["pragmatism over correctness"](https://github.com/Slackadays/Clipboard/wiki/Clipboard-Goals) which means we can break the rules when it means we can create a better UX or overall product, and we are already breaking the rules in favor of UX in other areas too, so there's that.

> Hm, since there are only CI tests for Linux, Windows, and Mac I kind of assumed those were the main targets and everything else was a "bonus".

We can blame this on GitHub. They only offer Actions for these three platforms, and even for self-hosted Actions they still only support those three. There was a special bespoke cross-compilation setup I had for compiling [Hajime](https://github.com/Slackadays/Hajime) for FreeBSD, but it was a nightmare to keep up with all the dependencies it used.

> I wouldn't really know where to start in supporting them without a lot of research and testing.

From checking the Linux manpage for `dlopen`, it looks like these functions are built into POSIX which means we can expect them to behave the same (hopefully) on anything that tries to be POSIX-compliant, which is most (all?) of the BSDs, where Linux is actually the outlier. That's why one of Clipboard's constraints is that it has to only use C++20 and zero external dependencies where possible so that we adhere to only standardized features that all these platforms share, unless we have to use a POSIX/Windows function. Overall, sticking to just C++20, POSIX, and Windows covers 99.9% of everything out there.

**Comment by Davipb** [comment]
> From checking the Linux manpage for `dlopen`, it looks like these functions are built into POSIX which means we can expect them to behave the same (hopefully) on anything that tries to be POSIX-compliant, which is most (all?) of the BSDs, where Linux is actually the outlier. 

Well right now I'm just defining "LINUX" as "UNIX AND NOT APPLE" in CMakeLists.txt. If the code works as-is on POSIX systems, could I just renamed that variable to "POSIX" and the associated file to `posix.cpp` and have everything stay compatible then?

**Comment by Slackadays** [comment]
That sounds like the most reasonable option, as POSIX is clearly something different from LINUX and APPLE.

**Comment by Davipb** [comment]
Done 🫡

**Pull request merged**
