### PR TITLE
Implement file copies and large text copies for X11

### PR DESCRIPTION
**Pull request by Davipb**
This PR finishes the X11 copy implementation by supporting large text copies and file copies. It also unifies the Windows and X11 clipboard copy handling so they can both share the same logic (don't empty temp dir if the files being copied are inside of it, don't copy files that don't exist, etc).

Note that unlike text copying, there doesn't seem to be a clear consensus on how to store file paths in the X11 clipboard. The code here handles the two most common types I could find experimenting around: `x-special/gnome-copied-files` and `text/uri-list`.

### CODE REVIEW

**Comment by Slackadays** [comment]
I like the unification of X11 and Windows! This should make things simpler all around.

**Comment by Slackadays** [comment]
One thing I noticed when thinking about how pasting is going to be implemented is that the indicator thread PR that got merged recently changes how CB exits, and so it could take a couple changes there to ensure CB can fork and become a daemon. However, there's nothing in the code that says this shouldn't be too hard, as forking will let the main thread exit on its own, but the child can stay in the `updateGUIClipboard` section. The `sync` step can search for CB's existing process and kill it if that's how repetitive operations are usually implemented.

**Comment by Davipb** [comment]
In theory there shouldn't be any issues, since the main process would continue as usual while the forked process would be created without any background threads and just `exit()` before returning control to the code in `clipboard.cpp`. But we'll see what happens when theory meets reality.

**Comment by Davipb** [comment]
Also, the paste daemon generated by `fork()` would automatically exit when another process steals ownership of the clipboard selection or when it loses connection to the X daemon, so we wouldn't need to search for processes and kill them during sync: just by spawning a new daemon and stealing ownership of the clipboard selection, the old daemon will get a notification and exit on its own.

**Pull request merged**
