### PR TITLE
Turkish translations

### PR DESCRIPTION
**Pull request by Zaryob**
I added Turkish translations.

### CODE REVIEW

**Comment by Slackadays** [comment]
This reminded me to make the latest Clipboard messages variables, so check the latest commit to account for those too before we can merge this

**Comment by Zaryob** [comment]
> This reminded me to make the latest Clipboard messages variables, so check the latest commit to account for those too before we can merge this

Thats why it is WIP right now 😃 I'm going to merge it

**Comment by Slackadays** [comment]
It looks ready to merge to me, do you feel the same way?

**Comment by Slackadays** [comment]
I noticed there are still several lines missing (clear_success, clear_fail, not_enough_storage) so you might want to check those too. See https://github.com/Slackadays/Clipboard/commit/9fba1f1bfe5dfd25f1c0ace4443139166d38f4bc

**Comment by Zaryob** [comment]
It is ready to launch.

**Comment by Slackadays** [comment]
@Zaryob Would it be possible to add a Turkish readme? I just added a Spanish readme and you can use that as a guide

**Pull request merged**
